spring:
  application:
    name: app-comisaria
  webflux:
    base-path: /app/comisaria/v1
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: appcomisaria
      uri: mongodb+srv://saintwil

api_comisaria:
  url_dpto: https://seguridadciudadana.mininter.gob.pe/arcgis/rest/services/visor/limtes_administrativos/MapServer/0/query?f=json&maxAllowableOffset=4891.969810250004&orderByFields=objectid&outFields=*&outSR=102100&resultType=tile&returnCentroid=true&returnExceededLimitFeatures=false&spatialRel=esriSpatialRelIntersects&where=1%3D1&geometryType=esriGeometryEnvelope&inSR=102100
  url_prov: https://seguridadciudadana.mininter.gob.pe/arcgis/rest/services/visor/limtes_administrativos/MapServer/1/query?f=json&orderByFields=provincia&outFields=*&spatialRel=esriSpatialRelIntersects&where=id_dpto%3D%27{id_dpto}%27
  url_dist: https://seguridadciudadana.mininter.gob.pe/arcgis/rest/services/visor/limtes_administrativos/MapServer/2/query?f=json&orderByFields=distrito&outFields=*&spatialRel=esriSpatialRelIntersects&where=id_prov%3D%27{id_prov}%27
  url_comisaria_count: https://seguridadciudadana.mininter.gob.pe/arcgis/rest/services/servicios_ogc/policia_nacional_peru/MapServer/5/query?f=json&returnIdsOnly=true&returnCountOnly=true&spatialRel=esriSpatialRelIntersects&where=1%3D1
  url_comisaria: https://seguridadciudadana.mininter.gob.pe/arcgis/rest/services/servicios_ogc/policia_nacional_peru/MapServer/5/query?f=json&cacheHint=true&resultOffset=0&resultRecordCount={total}&where=1%3D1&orderByFields=objectid&outFields=*&outSR=102100&spatialRel=esriSpatialRelIntersects
  host: seguridadciudadana.mininter.gob.pe
  origin: https://aplicaciones.mininter.gob.pe
server:
  port: 8091
